# Generated by Django 6.1.1 on 2026-09-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('especialidad', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('activo_ahora', models.BooleanField(default=True)),
                ('disponible_fin_semana', models.BooleanField(default=False)),
            ],
        ),
    ]
